USE QuizDB;

INSERT INTO User(id,username,FName,LName,numOffenses,email) VALUES (1,'mellit0','Mersey','Ellit',0,'mellit0@alibaba.com');
INSERT INTO User(id,username,FName,LName,numOffenses,email) VALUES (2,'scattlow1','Sydney','Cattlow',3,'scattlow1@cisco.com');
INSERT INTO User(id,username,FName,LName,numOffenses,email) VALUES (3,'mguitte2','Maighdiln','Guitte',2,'mguitte2@qq.com');
INSERT INTO User(id,username,FName,LName,numOffenses,email) VALUES (4,'rbrumwell3','Reilly','Brumwell',0,'rbrumwell3@answers.com');
INSERT INTO User(id,username,FName,LName,numOffenses,email) VALUES (5,'pdwerryhouse4','Philly','Dwerryhouse',2,'pdwerryhouse4@latimes.com');
INSERT INTO User(id,username,FName,LName,numOffenses,email) VALUES (6,'rhanks5','Raynard','Hanks',3,'rhanks5@sciencedaily.com');
INSERT INTO User(id,username,FName,LName,numOffenses,email) VALUES (7,'pnormadell6','Putnam','Normadell',0,'pnormadell6@sciencedaily.com');
INSERT INTO User(id,username,FName,LName,numOffenses,email) VALUES (8,'mfaloon7','Morry','Faloon',1,'mfaloon7@google.it');
INSERT INTO User(id,username,FName,LName,numOffenses,email) VALUES (9,'mventris8','Mirabelle','Ventris',0,'mventris8@china.com.cn');
INSERT INTO User(id,username,FName,LName,numOffenses,email) VALUES (10,'ascholfield9','Amery','Scholfield',3,'ascholfield9@businessweek.com');
INSERT INTO User(id,username,FName,LName,numOffenses,email) VALUES (11,'btwelftreea','Becky','Twelftree',3,'btwelftreea@sbwire.com');
INSERT INTO User(id,username,FName,LName,numOffenses,email) VALUES (12,'breddyb','Basia','Reddy',0,'breddyb@patch.com');
INSERT INTO User(id,username,FName,LName,numOffenses,email) VALUES (13,'lrodingerc','Lauryn','Rodinger',2,'lrodingerc@va.gov');
INSERT INTO User(id,username,FName,LName,numOffenses,email) VALUES (14,'kstigelld','Kareem','Stigell',0,'kstigelld@storify.com');
INSERT INTO User(id,username,FName,LName,numOffenses,email) VALUES (15,'fonowlane','Fernando','O''Nowlan',0,'fonowlane@japanpost.jp');
INSERT INTO User(id,username,FName,LName,numOffenses,email) VALUES (16,'ephilippartf','Edouard','Philippart',1,'ephilippartf@pcworld.com');
INSERT INTO User(id,username,FName,LName,numOffenses,email) VALUES (17,'tbernaldezg','Ted','Bernaldez',0,'tbernaldezg@youtube.com');
INSERT INTO User(id,username,FName,LName,numOffenses,email) VALUES (18,'hprandoh','Hurley','Prando',0,'hprandoh@google.com.au');
INSERT INTO User(id,username,FName,LName,numOffenses,email) VALUES (19,'bmonardi','Bessy','Monard',2,'bmonardi@zimbio.com');
INSERT INTO User(id,username,FName,LName,numOffenses,email) VALUES (20,'mnoquetj','Maddi','Noquet',1,'mnoquetj@homestead.com');
